name: Deploy to Blot

on:
  push:
    branches: [main]

jobs:
  relay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Blot
        run: |
          git push "https://${{ secrets.BLOT_USERNAME }}:${{ secrets.BLOT_PASSWORD }}@blot.im/${{ secrets.BLOT_REPO_PATH }}.git" HEAD:master --force
